"""empty message

Revision ID: 1959b5bff570
Revises: 
Create Date: 2018-05-11 09:08:50.311551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1959b5bff570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shorturl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('short_key', sa.String(length=30), nullable=True),
    sa.Column('original_url', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shorturl')
    # ### end Alembic commands ###
